version: 2.0

jobs:
  build:
    machine:
      enabled: true
    steps:
      # do nothing
      - run: echo NO-OP

  deploy:
    machine:
      enabled: true
    environment:
      - HEROKU_APP_NAME: splslack-bot
    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
